# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.provider 'virtualbox' do |v|
    v.memory = 4096
    v.cpus = 2
  end

  config.vm.define 'centos7' do |cent|

    cent.vm.box = "centos/7"

    cent.vm.box_check_update = true

    # With the line commented in Vagrant v 1.8.1,
    # ``vagrant up`` gives this error:
    #
    # No base MAC address was specified. This is required for the NAT networking
    # to work properly (and hence port forwarding, SSH, etc.). Specifying this
    # MAC address is typically up to the box and box maintainer. Please contact
    # the relevant person to solve this issue.
    #
    # The error doesn't show when ``vagrant up`` is run a second time
    # e.g. ``vagrant up; vagrant up``
    cent.vm.base_mac = "000AAAAAAAAA"

    # cent.vm.guest = :centos

    cent.vm.hostname = "centos7seagull"

    # With the line uncommented in Vagrant v 1.8.1,
    # ``vagrant up`` gives this error:
    #
    # The following SSH command responded with a non-zero exit status.
    # Vagrant assumes that this means the command failed!
    # dhclient em1
    # Stdout from the command:
    # Stderr from the command:
    # dhclient already running, pid: 387.
    # exiting.
    #

    cent.vm.network "private_network", type: "dhcp"

    cent.vm.synced_folder ".", "/vagrant_data", disabled: true

    cent.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "../ansible/play.yml"
    end
  end
end
